# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: wcs
  pool: 5
  host: 127.0.0.1
  username: root
  password: 

staging:
  adapter: mysql2
  encoding: utf8
  database: wcs
  pool: 5
  host: wcs.ckvm5xby4his.us-east-1.rds.amazonaws.com:3306
  username: root
  password: Test1234

production:
  adapter: mysql2
  encoding: utf8
  database: wcs
  pool: 5
  host: wcs.ckvm5xby4his.us-east-1.rds.amazonaws.com:3306
  username: root
  password: Test1234

